CREATE TABLE MENU(
idx INT PRIMARY KEY AUTO_INCREMENT,
memID VARCHAR(255),
title VARCHAR(255),
content VARCHAR(255),
writer VARCHAR(255),
indate VARCHAR(255),
count VARCHAR(255)
);
CREATE TABLE USERS(
idx INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(255),
password VARCHAR(255),
writer VARCHAR(255),
role VARCHAR(20),
CHECK (role IN ('ADMIN', 'MANAGER', 'MEMBER'))
);
ALTER TABLE menu ALTER COLUMN COUNT TYPE INT;
ALTER TABLE menu ALTER COLUMN count INT NOT NULL DEFAULT 0;